server:
  port: 8671
spring:
  profiles:
    eureka-server1
  application:
    name: eureka-server1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:8672/eureka/
  instance:
    hostname: eureka-server1
