server:
  port: 8671
  address: eureka-server1

spring:
  profiles:
    eureka-server1
  application:
    name: eureka-server1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8671/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: eureka-server1